### ISSUE TITLE
몽 이벤트 DB 스케쥴러

### ISSUE THREAD

**Issue by donowhy** [MongLife/spring_backend#100]
## 개요
- 이벤트 DB 를 순회하면서 확인 스케줄러
- 순회 중 190 분 이상 차이나면 순회 종료
- 180분 지나, Mong 체크 했을 때도 0으로 그대로 일 경우 몽 상태 변경

## 참고 사항
- related issue: #98 
- related branch: ```feat/management/schedule```

## 고려 사항
- 이벤트 스케쥴러 중 180분이 아니라 그 사이에 0 초과가 됐을 때, 시간 초기화 필요.
- 앞선 스케줄러와 함께 좀 더 복잡한 스케줄러 필요. -> 추가 개선 필요

**Comment by tableMinPark** [comment]
몽 기능 개발 완료로 인해 이슈를 닫습니다.
