### ISSUE TITLE
Kafka Config 

### ISSUE THREAD

**Issue by donowhy** [MongLife/spring_backend#37]
## 개요
- 각 서비스간 신뢰성있는 통신을 위해 kafka 연결을 진행합니다.

## 참고사항
- related issue: 
- related branch: ```feat/management/service/API```

**Comment by tableMinPark** [comment]
pub-sub 서버는 기존에 안드로이드와 통신을 위한 MQTT 로 구축하여 진행하겠습니다.

Kafka 는 추후 다시 이슈를 생성하여 진행하도록 하겠습니다.
