### ISSUE TITLE
몽 배변 치우기

### ISSUE THREAD

**Issue by donowhy** [MongLife/spring_backend#85]
## 개요
- Mong Poop 0으로 치우기를 진행합니다.
- 서비스, 컨트롤러 단 단위 테스트를 진행합니다.

## 참고 사항
- related issue: 
- related branch: ```feat/management/toCleanMongsPoop```

**Comment by tableMinPark** [comment]
몽 기능 개발 완료로 인해 이슈를 닫습니다.
