### ISSUE TITLE
몽 훈련

### ISSUE THREAD

**Issue by donowhy** [MongLife/spring_backend#86]
## 개요
- Mong 훈련을 진행합니다.
- 서비스, 컨트롤러 단 단위 테스트를 진행합니다.
- 추가적인 세부사항 결정 후 리팩토링 하겠습니다.

## 참고 사항
- related issue: 
- related branch: ```feat/management/mongTraining```

**Comment by tableMinPark** [comment]
몽 기능 개발 완료로 인해 이슈를 닫습니다.
