### ISSUE TITLE
몽 재우기/깨우기 기능 개발

### ISSUE THREAD

**Issue by donowhy** [MongLife/spring_backend#89]
## 개요
- API 호출 시, 현재 시간과 설정된 몽 생명 주기를 확인하여 수면과 기상을 변경합니다.
- 서비스, 컨트롤러 단 단위 테스트를 진행합니다.

## 참고 사항
- related issue: 
- related branch: ```feat/management/sleep```

**Comment by tableMinPark** [comment]
몽 기능 개발 완료로 인해 이슈를 닫습니다.
