### ISSUE TITLE
Management 리팩토링 및 도메인 추가

### ISSUE THREAD

**Issue by donowhy** [MongLife/spring_backend#96]
## 개요
- 회의에서 도출된 내용으로 인한 Management 리팩토링
- 음식 도메인, 몽이 먹은 음식 기록 도메인

## 이후 필요/고민할 요소
- A 이벤트가 발생 후 추적할 도메인 개발 필요

**Comment by tableMinPark** [comment]
몽 기능 개발 완료로 인해 이슈를 닫습니다.
